version: '2.1'
services:
  mongodb:
    image: mongo:3.2.11
    volumes:
      - mongodb:/data/db/

  backend:
    depends_on:
      - mongodb
    image: mkuzmin/todo-backend:${BACKEND_VERSION}
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/people
    ports:
      - "8080:8080"

  frontend:
    depends_on:
      - backend
    image: mkuzmin/todo-frontend:${FRONTEND_VERSION}
    ports:
      - "80:80"

volumes:
  mongodb:
